apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: milovicvojin/auth-provider
      context: auth-provider
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.java"
            dest: .
    - image: milovicvojin/auth-provider-client
      context: auth-provider-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
