server:
  port: 3000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: codedepo
    password: password
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
    jwt-private: |-
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeFOUSX4MV5YKD
      CnoCDLar9xbqoOAti0tEz8snM+81Dj8mQUuuSTQeNDfsBdMWUQL4/mfl8qkbtEfe
      7BXSI6iWhHtiys/NqhYmX1/bfe+M7qfspYd3McImC9S1m5s4/jPcWnpTATATt4Oc
      8u3mHzL+Pa7sPjGb2ftrxPdb6UQn2GS+TPbfE1rdQATS5xU7GgAbtKA9XKLLky+K
      MEILSHYtTxNDsalkvqofZe0LnJiYZZEdSRFFuvjhWuW5KKbbKfwcqs8pZb/u2B7g
      hMkOq16+sDJVDPqW2fotqy7HN/vYAangnr2B9bbz+A+yU9hvQmXjWUuSAXs8bv9t
      8WzctdMxAgMBAAECggEAe/QHo0iiHr+aJ8/aJ3i3IKZqKQ0f8uuzWDXuuvPWyLMp
      9g0t05pSN6WHrPnXRrZyxU0h6ouVbbwi/T6iM0bp2xEY2Rw//he4AzTqiNTytqOi
      IIiHYrToG1oxICg47AeeJJhvfBLGpcqg8CH7PJ0fVh5RmtRf1hBFr3IhajB5dQ7d
      I3fpqbyi2VNhqjwM9ArVDJaiSagyiBg4SGVXyNL9P0CpNr1xebED5CaiG4ckfd4M
      69UcyXHAkaBaUylP0vr462ROPNHUTLGt4SQLJ8nsphNzxMhkQz59myOxKgtc4GJb
      DwduQK6m+d6PAoyPs5FgOk7TMzyCJkDJJW+pjpG6AQKBgQD7ypA4b4wQB/xnum9W
      0lJbUhLzPKHgEDZp/fi6SUakp6WpAcr9hLEIvc9uDRHRc/kc13Ezzg5AJUJ5mInV
      aqpiUi5RqkKAHfIPIF1e/bHgg/cnFfqcNFwuUXWSPReE8XUQS7pBrVgPd5688YoO
      DfYCAHYIpEzjuaTsOgnvcRw9YQKBgQDhyzOJT+ZicH9TSqKmjPMqw9MxAB/PueT5
      joBFoJrHPVNNN7asf0RQIHoH+c8wSAyqn9gnmzIQnrHtzpX+OJwD/ANyJOQSkRQ7
      5EfxBwzR7NByu3hJzCvWXFDZBBDdgEjmXCp0CInrtDbwshSN55mdFnBOgr3a78Vw
      bcwwSaQX0QKBgDEO4ZStXyvMcog/UewnpHY4goqz2JJQdlmmayzYlBQGugc42zUU
      Am5ClUTK9RrLLtFIxLykPDCRUedhKhHT64imnHG666QMsZny415bramh7KjH5oFC
      zmcT5gVtM8TqSrW3G34qaQrycpI7uXtNiw4OyvCaGoUQKasBD+iAMFFhAoGAeBM7
      4PXgqtDwpTa3sKKcXk2tbg2G3U0ae6xQgraaGQJ/3jyWpL05cvMSclNi32Yxdjtz
      E/zwbu416SVHlt47+dJ3cqgzsbv9aqxHpeH961VotNsFaRlu5pxJUl9bKLAkFH1H
      BlXUIsi/vti1HZHgmy1npBjbJicEdHmvcK542UECgYEA2VOiwR7dsTY+3XUo7wKN
      NaXDE9XmD75cc/2aPVNoTwS/Xzo6Z2idArWEqJUElArnf6tBPQ/wMYifYf9XlCfL
      RxtSP89Lo6hF6LE4wRocYbovhnD2siPfwq1B4z3YL55rBi9Co8rzV/PjkG0pCUC7
      HhgTOpzptLxoXCFeJStBg9w=
    jwt-public: |-
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3hTlEl+DFeWCgwp6Agy2
      q/cW6qDgLYtLRM/LJzPvNQ4/JkFLrkk0HjQ37AXTFlEC+P5n5fKpG7RH3uwV0iOo
      loR7YsrPzaoWJl9f233vjO6n7KWHdzHCJgvUtZubOP4z3Fp6UwEwE7eDnPLt5h8y
      /j2u7D4xm9n7a8T3W+lEJ9hkvkz23xNa3UAE0ucVOxoAG7SgPVyiy5MvijBCC0h2
      LU8TQ7GpZL6qH2XtC5yYmGWRHUkRRbr44VrluSim2yn8HKrPKWW/7tge4ITJDqte
      vrAyVQz6ltn6Lasuxzf72AGp4J69gfW28/gPslPYb0Jl41lLkgF7PG7/bfFs3LXT
      MQIDAQAB
  main:
    web-application-type: servlet

